# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graph_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReadLoggerDataWindow(object):
    def setupUi(self, ReadLoggerDataWindow):
        ReadLoggerDataWindow.setObjectName("ReadLoggerDataWindow")
        ReadLoggerDataWindow.resize(908, 570)
        ReadLoggerDataWindow.setAutoFillBackground(False)
        ReadLoggerDataWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(ReadLoggerDataWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.comboBox_temp_unit = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.comboBox_temp_unit.setFont(font)
        self.comboBox_temp_unit.setStyleSheet("QComboBox{\n"
"    padding: 1px 18px 1px 3px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    padding: 1px 2px 1px 2px;\n"
"}")
        self.comboBox_temp_unit.setObjectName("comboBox_temp_unit")
        self.comboBox_temp_unit.addItem("")
        self.comboBox_temp_unit.addItem("")
        self.comboBox_temp_unit.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_temp_unit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.MplWidget = MplWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MplWidget.sizePolicy().hasHeightForWidth())
        self.MplWidget.setSizePolicy(sizePolicy)
        self.MplWidget.setMinimumSize(QtCore.QSize(880, 374))
        self.MplWidget.setObjectName("MplWidget")
        self.verticalLayout_2.addWidget(self.MplWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.graph_start = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graph_start.sizePolicy().hasHeightForWidth())
        self.graph_start.setSizePolicy(sizePolicy)
        self.graph_start.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.graph_start.setFont(font)
        self.graph_start.setObjectName("graph_start")
        self.gridLayout.addWidget(self.graph_start, 1, 1, 1, 1)
        self.graph_start_dt = QtWidgets.QLabel(self.centralwidget)
        self.graph_start_dt.setObjectName("graph_start_dt")
        self.gridLayout.addWidget(self.graph_start_dt, 1, 3, 1, 1)
        self.graph_end = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graph_end.sizePolicy().hasHeightForWidth())
        self.graph_end.setSizePolicy(sizePolicy)
        self.graph_end.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.graph_end.setFont(font)
        self.graph_end.setObjectName("graph_end")
        self.gridLayout.addWidget(self.graph_end, 2, 1, 1, 1)
        self.graph_end_dt = QtWidgets.QLabel(self.centralwidget)
        self.graph_end_dt.setObjectName("graph_end_dt")
        self.gridLayout.addWidget(self.graph_end_dt, 2, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 2, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        spacerItem1 = QtWidgets.QSpacerItem(678, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btn_save_csv_data = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save_csv_data.setMinimumSize(QtCore.QSize(110, 0))
        self.btn_save_csv_data.setStyleSheet("QPushButton{\n"
"    margine:5px;\n"
"    padding: 8px;\n"
"}")
        self.btn_save_csv_data.setObjectName("btn_save_csv_data")
        self.horizontalLayout.addWidget(self.btn_save_csv_data)
        self.btn_generate_report = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_generate_report.sizePolicy().hasHeightForWidth())
        self.btn_generate_report.setSizePolicy(sizePolicy)
        self.btn_generate_report.setMinimumSize(QtCore.QSize(110, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.btn_generate_report.setFont(font)
        self.btn_generate_report.setStyleSheet("QPushButton{\n"
"    margine:5px;\n"
"    padding: 8px;\n"
"}")
        self.btn_generate_report.setObjectName("btn_generate_report")
        self.horizontalLayout.addWidget(self.btn_generate_report)
        spacerItem2 = QtWidgets.QSpacerItem(40, 18, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        ReadLoggerDataWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ReadLoggerDataWindow)
        self.statusbar.setObjectName("statusbar")
        ReadLoggerDataWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(ReadLoggerDataWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 908, 21))
        self.menubar.setObjectName("menubar")
        ReadLoggerDataWindow.setMenuBar(self.menubar)

        self.retranslateUi(ReadLoggerDataWindow)
        QtCore.QMetaObject.connectSlotsByName(ReadLoggerDataWindow)

    def retranslateUi(self, ReadLoggerDataWindow):
        _translate = QtCore.QCoreApplication.translate
        ReadLoggerDataWindow.setWindowTitle(_translate("ReadLoggerDataWindow", "MainWindow"))
        self.label.setText(_translate("ReadLoggerDataWindow", "Temperature Unit : "))
        self.comboBox_temp_unit.setToolTip(_translate("ReadLoggerDataWindow", "<html><head/><body><p>Change unit</p></body></html>"))
        self.comboBox_temp_unit.setCurrentText(_translate("ReadLoggerDataWindow", "Celsius"))
        self.comboBox_temp_unit.setItemText(0, _translate("ReadLoggerDataWindow", "Celsius"))
        self.comboBox_temp_unit.setItemText(1, _translate("ReadLoggerDataWindow", "Kelvin"))
        self.comboBox_temp_unit.setItemText(2, _translate("ReadLoggerDataWindow", "Fahrenheit"))
        self.label_4.setText(_translate("ReadLoggerDataWindow", ":"))
        self.graph_start.setText(_translate("ReadLoggerDataWindow", "Start"))
        self.graph_start_dt.setText(_translate("ReadLoggerDataWindow", "TextLabel"))
        self.graph_end.setText(_translate("ReadLoggerDataWindow", "End"))
        self.graph_end_dt.setText(_translate("ReadLoggerDataWindow", "TextLabel"))
        self.label_5.setText(_translate("ReadLoggerDataWindow", ":"))
        self.btn_save_csv_data.setText(_translate("ReadLoggerDataWindow", "Save Data"))
        self.btn_generate_report.setText(_translate("ReadLoggerDataWindow", "Generate Report"))
from mplwidget import MplWidget
