# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graph_window2.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReadLoggerDataWindow(object):
    def setupUi(self, ReadLoggerDataWindow):
        ReadLoggerDataWindow.setObjectName("ReadLoggerDataWindow")
        ReadLoggerDataWindow.resize(908, 570)
        ReadLoggerDataWindow.setAutoFillBackground(False)
        ReadLoggerDataWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(ReadLoggerDataWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.comboBox_temp_unit = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.comboBox_temp_unit.setFont(font)
        self.comboBox_temp_unit.setStyleSheet("QComboBox{\n"
"    padding: 1px 18px 1px 3px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    padding: 1px 2px 1px 2px;\n"
"}")
        self.comboBox_temp_unit.setObjectName("comboBox_temp_unit")
        self.comboBox_temp_unit.addItem("")
        self.comboBox_temp_unit.addItem("")
        self.comboBox_temp_unit.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_temp_unit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.MplWidget = MplWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MplWidget.sizePolicy().hasHeightForWidth())
        self.MplWidget.setSizePolicy(sizePolicy)
        self.MplWidget.setMinimumSize(QtCore.QSize(880, 374))
        self.MplWidget.setObjectName("MplWidget")
        self.verticalLayout_2.addWidget(self.MplWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.graph_start_dt = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graph_start_dt.sizePolicy().hasHeightForWidth())
        self.graph_start_dt.setSizePolicy(sizePolicy)
        self.graph_start_dt.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.graph_start_dt.setFont(font)
        self.graph_start_dt.setObjectName("graph_start_dt")
        self.verticalLayout.addWidget(self.graph_start_dt)
        self.graph_end_dt = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graph_end_dt.sizePolicy().hasHeightForWidth())
        self.graph_end_dt.setSizePolicy(sizePolicy)
        self.graph_end_dt.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.graph_end_dt.setFont(font)
        self.graph_end_dt.setObjectName("graph_end_dt")
        self.verticalLayout.addWidget(self.graph_end_dt)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(678, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btn_generate_report = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_generate_report.sizePolicy().hasHeightForWidth())
        self.btn_generate_report.setSizePolicy(sizePolicy)
        self.btn_generate_report.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.btn_generate_report.setFont(font)
        self.btn_generate_report.setStyleSheet("margine:5px;\n"
"padding: 8px;")
        self.btn_generate_report.setObjectName("btn_generate_report")
        self.horizontalLayout.addWidget(self.btn_generate_report)
        spacerItem2 = QtWidgets.QSpacerItem(40, 18, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        ReadLoggerDataWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ReadLoggerDataWindow)
        self.statusbar.setObjectName("statusbar")
        ReadLoggerDataWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(ReadLoggerDataWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 908, 20))
        self.menubar.setObjectName("menubar")
        ReadLoggerDataWindow.setMenuBar(self.menubar)

        self.retranslateUi(ReadLoggerDataWindow)
        QtCore.QMetaObject.connectSlotsByName(ReadLoggerDataWindow)

    def retranslateUi(self, ReadLoggerDataWindow):
        _translate = QtCore.QCoreApplication.translate
        ReadLoggerDataWindow.setWindowTitle(_translate("ReadLoggerDataWindow", "MainWindow"))
        self.label.setText(_translate("ReadLoggerDataWindow", "Temperature Unit : "))
        self.comboBox_temp_unit.setToolTip(_translate("ReadLoggerDataWindow", "<html><head/><body><p>Change unit</p></body></html>"))
        self.comboBox_temp_unit.setCurrentText(_translate("ReadLoggerDataWindow", "Celsius"))
        self.comboBox_temp_unit.setItemText(0, _translate("ReadLoggerDataWindow", "Celsius"))
        self.comboBox_temp_unit.setItemText(1, _translate("ReadLoggerDataWindow", "Kelvin"))
        self.comboBox_temp_unit.setItemText(2, _translate("ReadLoggerDataWindow", "Fahrenheit"))
        self.graph_start_dt.setText(_translate("ReadLoggerDataWindow", "End :"))
        self.graph_end_dt.setText(_translate("ReadLoggerDataWindow", "Start :"))
        self.btn_generate_report.setText(_translate("ReadLoggerDataWindow", "Generate Report"))
from mplwidget import MplWidget
