# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(518, 725)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(100, 50))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Canada))
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_device_id = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.label_device_id.setFont(font)
        self.label_device_id.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_device_id.setText("")
        self.label_device_id.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_device_id.setObjectName("label_device_id")
        self.gridLayout.addWidget(self.label_device_id, 1, 1, 1, 2)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.scrollArea.setFont(font)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 500, 596))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_hum = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_hum.setFont(font)
        self.label_hum.setObjectName("label_hum")
        self.gridLayout_2.addWidget(self.label_hum, 37, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_battery_level = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_battery_level.setFont(font)
        self.label_battery_level.setText("")
        self.label_battery_level.setObjectName("label_battery_level")
        self.horizontalLayout_2.addWidget(self.label_battery_level)
        self.label_battery_level_low_signal = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_battery_level_low_signal.setFont(font)
        self.label_battery_level_low_signal.setText("")
        self.label_battery_level_low_signal.setObjectName("label_battery_level_low_signal")
        self.horizontalLayout_2.addWidget(self.label_battery_level_low_signal)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 8, 2, 1, 3)
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.line.setFont(font)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 12, 0, 1, 5)
        self.label_temp = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_temp.setFont(font)
        self.label_temp.setObjectName("label_temp")
        self.gridLayout_2.addWidget(self.label_temp, 36, 0, 1, 1)
        self.label_d_id_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_d_id_5.setFont(font)
        self.label_d_id_5.setObjectName("label_d_id_5")
        self.gridLayout_2.addWidget(self.label_d_id_5, 23, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 38, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 29, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 28, 0, 1, 1)
        self.btn_set_alarm = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_set_alarm.sizePolicy().hasHeightForWidth())
        self.btn_set_alarm.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.btn_set_alarm.setFont(font)
        self.btn_set_alarm.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_set_alarm.setObjectName("btn_set_alarm")
        self.gridLayout_2.addWidget(self.btn_set_alarm, 37, 4, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 23, 1, 1, 1)
        self.comboBox_logging_stop = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_logging_stop.sizePolicy().hasHeightForWidth())
        self.comboBox_logging_stop.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.comboBox_logging_stop.setFont(font)
        self.comboBox_logging_stop.setObjectName("comboBox_logging_stop")
        self.comboBox_logging_stop.addItem("")
        self.comboBox_logging_stop.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_logging_stop, 27, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 19, 0, 1, 1)
        self.checkBox_temp_alarm_status = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_temp_alarm_status.setFont(font)
        self.checkBox_temp_alarm_status.setObjectName("checkBox_temp_alarm_status")
        self.gridLayout_2.addWidget(self.checkBox_temp_alarm_status, 34, 0, 1, 5)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 17, 1, 1, 1)
        self.lineEdit_high_hum = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lineEdit_high_hum.setFont(font)
        self.lineEdit_high_hum.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_high_hum.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.lineEdit_high_hum.setObjectName("lineEdit_high_hum")
        self.gridLayout_2.addWidget(self.lineEdit_high_hum, 37, 2, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lbl_device_id = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lbl_device_id.setText("")
        self.lbl_device_id.setObjectName("lbl_device_id")
        self.horizontalLayout_6.addWidget(self.lbl_device_id)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 2, 2, 1, 3)
        self.line_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.line_3.setFont(font)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setObjectName("line_3")
        self.gridLayout_2.addWidget(self.line_3, 31, 0, 1, 5)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 11, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 2, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 18, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 37, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 16, 1, 1, 1)
        self.label_low_value = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_low_value.setFont(font)
        self.label_low_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_low_value.setObjectName("label_low_value")
        self.gridLayout_2.addWidget(self.label_low_value, 35, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 4, 4, 1, 1)
        self.label_d_id_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_d_id_6.setFont(font)
        self.label_d_id_6.setObjectName("label_d_id_6")
        self.gridLayout_2.addWidget(self.label_d_id_6, 16, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_logging_interval = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_logging_interval.sizePolicy().hasHeightForWidth())
        self.lineEdit_logging_interval.setSizePolicy(sizePolicy)
        self.lineEdit_logging_interval.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lineEdit_logging_interval.setFont(font)
        self.lineEdit_logging_interval.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_logging_interval.setText("")
        self.lineEdit_logging_interval.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_logging_interval.setObjectName("lineEdit_logging_interval")
        self.horizontalLayout.addWidget(self.lineEdit_logging_interval)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem5 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.gridLayout_2.addLayout(self.horizontalLayout, 23, 2, 1, 2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_device_type = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_device_type.setFont(font)
        self.label_device_type.setText("")
        self.label_device_type.setObjectName("label_device_type")
        self.horizontalLayout_4.addWidget(self.label_device_type)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 6, 2, 1, 3)
        self.label_title_battery_level = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_title_battery_level.setFont(font)
        self.label_title_battery_level.setObjectName("label_title_battery_level")
        self.gridLayout_2.addWidget(self.label_title_battery_level, 8, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 4, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 8, 1, 1, 1)
        self.label_title_device_id_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_title_device_id_2.setFont(font)
        self.label_title_device_id_2.setObjectName("label_title_device_id_2")
        self.gridLayout_2.addWidget(self.label_title_device_id_2, 4, 0, 1, 1)
        self.lineEdit_device_name = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lineEdit_device_name.setFont(font)
        self.lineEdit_device_name.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_device_name.setObjectName("lineEdit_device_name")
        self.gridLayout_2.addWidget(self.lineEdit_device_name, 9, 2, 1, 2)
        self.lineEdit_low_hum = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lineEdit_low_hum.setFont(font)
        self.lineEdit_low_hum.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_low_hum.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.lineEdit_low_hum.setObjectName("lineEdit_low_hum")
        self.gridLayout_2.addWidget(self.lineEdit_low_hum, 37, 3, 1, 1)
        self.lineEdit_low_pressure = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lineEdit_low_pressure.setFont(font)
        self.lineEdit_low_pressure.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_low_pressure.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.lineEdit_low_pressure.setObjectName("lineEdit_low_pressure")
        self.gridLayout_2.addWidget(self.lineEdit_low_pressure, 38, 3, 1, 1)
        self.label_title_device_type = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_title_device_type.setFont(font)
        self.label_title_device_type.setObjectName("label_title_device_type")
        self.gridLayout_2.addWidget(self.label_title_device_type, 6, 0, 1, 1)
        self.btn_set_logging_interval = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.btn_set_logging_interval.setFont(font)
        self.btn_set_logging_interval.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_set_logging_interval.setObjectName("btn_set_logging_interval")
        self.gridLayout_2.addWidget(self.btn_set_logging_interval, 23, 4, 1, 1)
        self.label_pressure = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_pressure.setFont(font)
        self.label_pressure.setObjectName("label_pressure")
        self.gridLayout_2.addWidget(self.label_pressure, 38, 0, 1, 1)
        self.label_d_id_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_d_id_7.setFont(font)
        self.label_d_id_7.setObjectName("label_d_id_7")
        self.gridLayout_2.addWidget(self.label_d_id_7, 17, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_device_time = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_device_time.setFont(font)
        self.label_device_time.setText("")
        self.label_device_time.setObjectName("label_device_time")
        self.horizontalLayout_7.addWidget(self.label_device_time)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 16, 2, 1, 2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_system_time = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_system_time.setFont(font)
        self.label_system_time.setText("")
        self.label_system_time.setObjectName("label_system_time")
        self.horizontalLayout_8.addWidget(self.label_system_time)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 17, 2, 1, 2)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem9, 39, 0, 1, 1)
        self.btn_set_start_stop_option = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_set_start_stop_option.sizePolicy().hasHeightForWidth())
        self.btn_set_start_stop_option.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.btn_set_start_stop_option.setFont(font)
        self.btn_set_start_stop_option.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_set_start_stop_option.setObjectName("btn_set_start_stop_option")
        self.gridLayout_2.addWidget(self.btn_set_start_stop_option, 26, 4, 2, 1)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 9, 1, 1, 1)
        self.checkBox_dst = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_dst.setFont(font)
        self.checkBox_dst.setObjectName("checkBox_dst")
        self.gridLayout_2.addWidget(self.checkBox_dst, 14, 0, 1, 5)
        self.lineEdit_high_pressure = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lineEdit_high_pressure.setFont(font)
        self.lineEdit_high_pressure.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_high_pressure.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.lineEdit_high_pressure.setObjectName("lineEdit_high_pressure")
        self.gridLayout_2.addWidget(self.lineEdit_high_pressure, 38, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 0, 0, 1, 5)
        self.lineEdit_high_temp = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lineEdit_high_temp.setFont(font)
        self.lineEdit_high_temp.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_high_temp.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.lineEdit_high_temp.setObjectName("lineEdit_high_temp")
        self.gridLayout_2.addWidget(self.lineEdit_high_temp, 36, 2, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.dateTimeEdit_logging_stop = QtWidgets.QDateTimeEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateTimeEdit_logging_stop.sizePolicy().hasHeightForWidth())
        self.dateTimeEdit_logging_stop.setSizePolicy(sizePolicy)
        self.dateTimeEdit_logging_stop.setMinimumSize(QtCore.QSize(0, 0))
        self.dateTimeEdit_logging_stop.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.dateTimeEdit_logging_stop.setFont(font)
        self.dateTimeEdit_logging_stop.setCalendarPopup(True)
        self.dateTimeEdit_logging_stop.setObjectName("dateTimeEdit_logging_stop")
        self.horizontalLayout_10.addWidget(self.dateTimeEdit_logging_stop)
        spacerItem10 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem10)
        self.gridLayout_2.addLayout(self.horizontalLayout_10, 27, 2, 1, 2)
        self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.line_2.setFont(font)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 20, 0, 1, 5)
        self.btn_erase_data = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.btn_erase_data.setFont(font)
        self.btn_erase_data.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_erase_data.setObjectName("btn_erase_data")
        self.gridLayout_2.addWidget(self.btn_erase_data, 4, 2, 1, 1)
        self.btn_device_rename = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.btn_device_rename.setFont(font)
        self.btn_device_rename.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_device_rename.setObjectName("btn_device_rename")
        self.gridLayout_2.addWidget(self.btn_device_rename, 9, 4, 1, 1)
        self.label_high_value = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_high_value.setFont(font)
        self.label_high_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_high_value.setObjectName("label_high_value")
        self.gridLayout_2.addWidget(self.label_high_value, 35, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 36, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem11, 10, 0, 1, 1)
        self.lineEdit_low_temp = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lineEdit_low_temp.setFont(font)
        self.lineEdit_low_temp.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_low_temp.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.lineEdit_low_temp.setObjectName("lineEdit_low_temp")
        self.gridLayout_2.addWidget(self.lineEdit_low_temp, 36, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 9, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 6, 1, 1, 1)
        self.label_title_device_information_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_title_device_information_2.setFont(font)
        self.label_title_device_information_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_title_device_information_2.setObjectName("label_title_device_information_2")
        self.gridLayout_2.addWidget(self.label_title_device_information_2, 2, 0, 1, 1)
        self.comboBox_logging_start = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_logging_start.sizePolicy().hasHeightForWidth())
        self.comboBox_logging_start.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.comboBox_logging_start.setFont(font)
        self.comboBox_logging_start.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.comboBox_logging_start.setObjectName("comboBox_logging_start")
        self.comboBox_logging_start.addItem("")
        self.comboBox_logging_start.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_logging_start, 26, 0, 1, 1)
        self.btn_reset_factory_settings = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.btn_reset_factory_settings.setFont(font)
        self.btn_reset_factory_settings.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_reset_factory_settings.setObjectName("btn_reset_factory_settings")
        self.gridLayout_2.addWidget(self.btn_reset_factory_settings, 4, 3, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.dateTimeEdit_logging_start = QtWidgets.QDateTimeEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateTimeEdit_logging_start.sizePolicy().hasHeightForWidth())
        self.dateTimeEdit_logging_start.setSizePolicy(sizePolicy)
        self.dateTimeEdit_logging_start.setMinimumSize(QtCore.QSize(0, 0))
        self.dateTimeEdit_logging_start.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.dateTimeEdit_logging_start.setFont(font)
        self.dateTimeEdit_logging_start.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(9999, 12, 29), QtCore.QTime(23, 59, 59)))
        self.dateTimeEdit_logging_start.setCalendarPopup(True)
        self.dateTimeEdit_logging_start.setObjectName("dateTimeEdit_logging_start")
        self.horizontalLayout_9.addWidget(self.dateTimeEdit_logging_start)
        spacerItem12 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem12)
        self.gridLayout_2.addLayout(self.horizontalLayout_9, 26, 2, 1, 2)
        self.line_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setObjectName("line_4")
        self.gridLayout_2.addWidget(self.line_4, 1, 0, 1, 5)
        self.btn_sync_device_system_time = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_sync_device_system_time.sizePolicy().hasHeightForWidth())
        self.btn_sync_device_system_time.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.btn_sync_device_system_time.setFont(font)
        self.btn_sync_device_system_time.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_sync_device_system_time.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btn_sync_device_system_time.setObjectName("btn_sync_device_system_time")
        self.gridLayout_2.addWidget(self.btn_sync_device_system_time, 16, 4, 2, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 2, 0, 1, 4)
        spacerItem13 = QtWidgets.QSpacerItem(10, 35, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem13, 3, 0, 1, 1)
        self.reconnect_button = QtWidgets.QPushButton(self.centralwidget)
        self.reconnect_button.setObjectName("reconnect_button")
        self.gridLayout.addWidget(self.reconnect_button, 1, 3, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 1, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.btn_real_time_data = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_real_time_data.sizePolicy().hasHeightForWidth())
        self.btn_real_time_data.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.btn_real_time_data.setFont(font)
        self.btn_real_time_data.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_real_time_data.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btn_real_time_data.setStyleSheet("QPushButton{\n"
"    background-color: rgb(16, 16, 16);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid white;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(40, 40, 40);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid white;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(20, 20, 20);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid white;\n"
"    border-radius: 10px;\n"
"    padding: 5px;;\n"
"}")
        self.btn_real_time_data.setFlat(False)
        self.btn_real_time_data.setObjectName("btn_real_time_data")
        self.gridLayout.addWidget(self.btn_real_time_data, 3, 2, 1, 1)
        self.btn_read_logger_data = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_read_logger_data.sizePolicy().hasHeightForWidth())
        self.btn_read_logger_data.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.btn_read_logger_data.setFont(font)
        self.btn_read_logger_data.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_read_logger_data.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btn_read_logger_data.setStyleSheet("QPushButton{\n"
"    background-color: rgb(16, 16, 16);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid white;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(40, 40, 40);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid white;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(20, 20, 20);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid white;\n"
"    border-radius: 10px;\n"
"    padding: 5px;;\n"
"}")
        self.btn_read_logger_data.setObjectName("btn_read_logger_data")
        self.gridLayout.addWidget(self.btn_read_logger_data, 3, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 518, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuStatus_LED = QtWidgets.QMenu(self.menuFile)
        self.menuStatus_LED.setObjectName("menuStatus_LED")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionGuide_to_using_CredoWare = QtWidgets.QAction(MainWindow)
        self.actionGuide_to_using_CredoWare.setObjectName("actionGuide_to_using_CredoWare")
        self.actionCSL_Series_Logger_detail_guide = QtWidgets.QAction(MainWindow)
        self.actionCSL_Series_Logger_detail_guide.setObjectName("actionCSL_Series_Logger_detail_guide")
        self.actionCredoSense_website = QtWidgets.QAction(MainWindow)
        self.actionCredoSense_website.setObjectName("actionCredoSense_website")
        self.actionStart_reading_logged_data = QtWidgets.QAction(MainWindow)
        self.actionStart_reading_logged_data.setObjectName("actionStart_reading_logged_data")
        self.actionRemove_all_logged_data = QtWidgets.QAction(MainWindow)
        self.actionRemove_all_logged_data.setObjectName("actionRemove_all_logged_data")
        self.actionStart_real_time_data_streaming = QtWidgets.QAction(MainWindow)
        self.actionStart_real_time_data_streaming.setObjectName("actionStart_real_time_data_streaming")
        self.actionSync_logger_to_computer_time = QtWidgets.QAction(MainWindow)
        self.actionSync_logger_to_computer_time.setObjectName("actionSync_logger_to_computer_time")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionTurn_ON = QtWidgets.QAction(MainWindow)
        self.actionTurn_ON.setObjectName("actionTurn_ON")
        self.actionTrun_OFF = QtWidgets.QAction(MainWindow)
        self.actionTrun_OFF.setObjectName("actionTrun_OFF")
        self.menuStatus_LED.addAction(self.actionTurn_ON)
        self.menuStatus_LED.addAction(self.actionTrun_OFF)
        self.menuFile.addAction(self.actionStart_reading_logged_data)
        self.menuFile.addAction(self.actionRemove_all_logged_data)
        self.menuFile.addAction(self.actionStart_real_time_data_streaming)
        self.menuFile.addAction(self.actionSync_logger_to_computer_time)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuStatus_LED.menuAction())
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionCSL_Series_Logger_detail_guide)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionCredoSense_website)
        self.menuHelp.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.comboBox_logging_start.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CredoWare"))
        self.label_hum.setText(_translate("MainWindow", "Humidity (%)"))
        self.label_temp.setText(_translate("MainWindow", "Temperature (C)"))
        self.label_d_id_5.setText(_translate("MainWindow", "Interval"))
        self.label_15.setText(_translate("MainWindow", ":"))
        self.label_4.setText(_translate("MainWindow", "Alarm Options"))
        self.btn_set_alarm.setToolTip(_translate("MainWindow", "Set alarm"))
        self.btn_set_alarm.setStatusTip(_translate("MainWindow", "Program the logger with these alarm values"))
        self.btn_set_alarm.setText(_translate("MainWindow", "Set Alarm Values"))
        self.label_16.setText(_translate("MainWindow", ":"))
        self.comboBox_logging_stop.setToolTip(_translate("MainWindow", "Logging stop option"))
        self.comboBox_logging_stop.setStatusTip(_translate("MainWindow", "Select if logging stops with the button press or at a specific time?"))
        self.comboBox_logging_stop.setItemText(0, _translate("MainWindow", "Button Stop"))
        self.comboBox_logging_stop.setItemText(1, _translate("MainWindow", "Stop At Time"))
        self.label_3.setText(_translate("MainWindow", "Logging Options"))
        self.checkBox_temp_alarm_status.setStatusTip(_translate("MainWindow", "Check and click on Set Alarm Values to enable"))
        self.checkBox_temp_alarm_status.setText(_translate("MainWindow", "Alarm Status (check and click Set Alarm Values to enable alarm)"))
        self.label_12.setText(_translate("MainWindow", ":"))
        self.lineEdit_high_hum.setToolTip(_translate("MainWindow", "Max 100"))
        self.lineEdit_high_hum.setStatusTip(_translate("MainWindow", "Maximum allowed value: 100"))
        self.lineEdit_high_hum.setPlaceholderText(_translate("MainWindow", "100"))
        self.label.setText(_translate("MainWindow", "Timekeeping Options"))
        self.label_9.setText(_translate("MainWindow", ":"))
        self.label_14.setText(_translate("MainWindow", ":"))
        self.label_10.setText(_translate("MainWindow", ":"))
        self.label_low_value.setText(_translate("MainWindow", "Low"))
        self.label_d_id_6.setText(_translate("MainWindow", "Logger\'s Time"))
        self.lineEdit_logging_interval.setToolTip(_translate("MainWindow", "1 to 1440"))
        self.lineEdit_logging_interval.setStatusTip(_translate("MainWindow", "Value should be integer and ranging from 1 to 1440"))
        self.lineEdit_logging_interval.setPlaceholderText(_translate("MainWindow", "1 to 1440"))
        self.label_2.setText(_translate("MainWindow", "Minute (s)"))
        self.label_title_battery_level.setText(_translate("MainWindow", "Main Battery Voltage"))
        self.label_5.setText(_translate("MainWindow", ":"))
        self.label_7.setText(_translate("MainWindow", ":"))
        self.label_title_device_id_2.setText(_translate("MainWindow", "Erase or Reset"))
        self.lineEdit_device_name.setToolTip(_translate("MainWindow", "Name"))
        self.lineEdit_device_name.setStatusTip(_translate("MainWindow", "Name of the connected logger"))
        self.lineEdit_device_name.setPlaceholderText(_translate("MainWindow", "CredoSense"))
        self.lineEdit_low_hum.setToolTip(_translate("MainWindow", "Min 0"))
        self.lineEdit_low_hum.setStatusTip(_translate("MainWindow", "Minimum allowed value: 0"))
        self.lineEdit_low_hum.setPlaceholderText(_translate("MainWindow", "0"))
        self.lineEdit_low_pressure.setToolTip(_translate("MainWindow", "Min 600"))
        self.lineEdit_low_pressure.setStatusTip(_translate("MainWindow", "Minimum allowed value: 600"))
        self.lineEdit_low_pressure.setPlaceholderText(_translate("MainWindow", "600"))
        self.label_title_device_type.setText(_translate("MainWindow", "Device Type"))
        self.btn_set_logging_interval.setToolTip(_translate("MainWindow", "Set interval"))
        self.btn_set_logging_interval.setStatusTip(_translate("MainWindow", "Program logging interval"))
        self.btn_set_logging_interval.setText(_translate("MainWindow", "Set Logging Interval"))
        self.label_pressure.setText(_translate("MainWindow", "Pressure (mbar)"))
        self.label_d_id_7.setText(_translate("MainWindow", "Computer\'s Time"))
        self.btn_set_start_stop_option.setToolTip(_translate("MainWindow", "Set start/stop"))
        self.btn_set_start_stop_option.setStatusTip(_translate("MainWindow", "Program logging start and stop options"))
        self.btn_set_start_stop_option.setText(_translate("MainWindow", "Set Start/Stop Option"))
        self.label_8.setText(_translate("MainWindow", ":"))
        self.checkBox_dst.setToolTip(_translate("MainWindow", "Enable DST"))
        self.checkBox_dst.setStatusTip(_translate("MainWindow", "Check to Enable daylight savings time"))
        self.checkBox_dst.setText(_translate("MainWindow", "Daylight Saving (check to enable daylight savings time)"))
        self.lineEdit_high_pressure.setToolTip(_translate("MainWindow", "Max 1200"))
        self.lineEdit_high_pressure.setStatusTip(_translate("MainWindow", "Maximum allowed value: 1200"))
        self.lineEdit_high_pressure.setPlaceholderText(_translate("MainWindow", "1200"))
        self.label_17.setText(_translate("MainWindow", "Device Information"))
        self.lineEdit_high_temp.setToolTip(_translate("MainWindow", "Max 85"))
        self.lineEdit_high_temp.setStatusTip(_translate("MainWindow", "Maximum allowed value: 85"))
        self.lineEdit_high_temp.setPlaceholderText(_translate("MainWindow", "85"))
        self.dateTimeEdit_logging_stop.setToolTip(_translate("MainWindow", "Stop date and time"))
        self.dateTimeEdit_logging_stop.setStatusTip(_translate("MainWindow", "Select when to stop logging"))
        self.dateTimeEdit_logging_stop.setDisplayFormat(_translate("MainWindow", "d MMM yyyy, hh:mm"))
        self.btn_erase_data.setToolTip(_translate("MainWindow", "Erase"))
        self.btn_erase_data.setStatusTip(_translate("MainWindow", "Erase all logged data"))
        self.btn_erase_data.setText(_translate("MainWindow", "Erase Data"))
        self.btn_device_rename.setToolTip(_translate("MainWindow", "Rename device"))
        self.btn_device_rename.setStatusTip(_translate("MainWindow", "Custom name the logger (maximum 255 characrers allowed)"))
        self.btn_device_rename.setText(_translate("MainWindow", "Rename"))
        self.label_high_value.setText(_translate("MainWindow", "High"))
        self.label_13.setText(_translate("MainWindow", ":"))
        self.lineEdit_low_temp.setToolTip(_translate("MainWindow", "Min -45"))
        self.lineEdit_low_temp.setStatusTip(_translate("MainWindow", "Minimum allowed value: -45"))
        self.lineEdit_low_temp.setPlaceholderText(_translate("MainWindow", "-45"))
        self.label_11.setText(_translate("MainWindow", "Device Name"))
        self.label_6.setText(_translate("MainWindow", ":"))
        self.label_title_device_information_2.setText(_translate("MainWindow", "Device Model"))
        self.comboBox_logging_start.setToolTip(_translate("MainWindow", "Logging start options"))
        self.comboBox_logging_start.setStatusTip(_translate("MainWindow", "Select if logging starts with the button press or at a specific time?"))
        self.comboBox_logging_start.setCurrentText(_translate("MainWindow", "Button Start"))
        self.comboBox_logging_start.setItemText(0, _translate("MainWindow", "Button Start"))
        self.comboBox_logging_start.setItemText(1, _translate("MainWindow", "Start At Time"))
        self.btn_reset_factory_settings.setToolTip(_translate("MainWindow", "Reset"))
        self.btn_reset_factory_settings.setStatusTip(_translate("MainWindow", "Reset the logger to default settings"))
        self.btn_reset_factory_settings.setText(_translate("MainWindow", "Factory Reset"))
        self.dateTimeEdit_logging_start.setToolTip(_translate("MainWindow", "Start date and time"))
        self.dateTimeEdit_logging_start.setStatusTip(_translate("MainWindow", "Select when to start logging"))
        self.dateTimeEdit_logging_start.setDisplayFormat(_translate("MainWindow", "d MMM yyyy, hh:mm"))
        self.btn_sync_device_system_time.setToolTip(_translate("MainWindow", "Sync time"))
        self.btn_sync_device_system_time.setStatusTip(_translate("MainWindow", "Sync date and time of the logger with this computer"))
        self.btn_sync_device_system_time.setText(_translate("MainWindow", "Sync Time"))
        self.reconnect_button.setToolTip(_translate("MainWindow", "Reestablish connection"))
        self.reconnect_button.setStatusTip(_translate("MainWindow", "Refresh the existing connection or reconnect to a new logger"))
        self.reconnect_button.setWhatsThis(_translate("MainWindow", "sdfj"))
        self.reconnect_button.setText(_translate("MainWindow", "Reconnect"))
        self.label_18.setText(_translate("MainWindow", " Connectivity Status:"))
        self.btn_real_time_data.setStatusTip(_translate("MainWindow", "Start real-time data streaming window"))
        self.btn_real_time_data.setText(_translate("MainWindow", "Real-time Data"))
        self.btn_read_logger_data.setStatusTip(_translate("MainWindow", "Read data saved in the logger"))
        self.btn_read_logger_data.setText(_translate("MainWindow", "Read Logged Data"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuStatus_LED.setTitle(_translate("MainWindow", "Status LED"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionExit.setText(_translate("MainWindow", "Quit"))
        self.actionExit.setStatusTip(_translate("MainWindow", "Exit CredoWare"))
        self.actionGuide_to_using_CredoWare.setText(_translate("MainWindow", "Guide to using CredoWare"))
        self.actionGuide_to_using_CredoWare.setStatusTip(_translate("MainWindow", "A detailed how to document on utilizing all functions of CredoWare"))
        self.actionGuide_to_using_CredoWare.setShortcut(_translate("MainWindow", "F1"))
        self.actionCSL_Series_Logger_detail_guide.setText(_translate("MainWindow", "CSL Series Logger user manual"))
        self.actionCSL_Series_Logger_detail_guide.setStatusTip(_translate("MainWindow", "A detail document on CSL seriesl loggers\' operation"))
        self.actionCSL_Series_Logger_detail_guide.setShortcut(_translate("MainWindow", "F1"))
        self.actionCredoSense_website.setText(_translate("MainWindow", "CredoSense website"))
        self.actionCredoSense_website.setStatusTip(_translate("MainWindow", "www.credosense.com"))
        self.actionStart_reading_logged_data.setText(_translate("MainWindow", "Start reading logged data"))
        self.actionStart_reading_logged_data.setStatusTip(_translate("MainWindow", "Read the data saved inside the logger connected to CreDock"))
        self.actionStart_reading_logged_data.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionRemove_all_logged_data.setText(_translate("MainWindow", "Remove all logged data"))
        self.actionRemove_all_logged_data.setStatusTip(_translate("MainWindow", "Remove all the data saved inside the logger"))
        self.actionRemove_all_logged_data.setShortcut(_translate("MainWindow", "Ctrl+Shift+Del"))
        self.actionStart_real_time_data_streaming.setText(_translate("MainWindow", "Start real-time data streaming"))
        self.actionStart_real_time_data_streaming.setStatusTip(_translate("MainWindow", "Open the real-time data streaming window"))
        self.actionStart_real_time_data_streaming.setShortcut(_translate("MainWindow", "Ctrl+Shift+R"))
        self.actionSync_logger_to_computer_time.setText(_translate("MainWindow", "Sync logger time"))
        self.actionSync_logger_to_computer_time.setStatusTip(_translate("MainWindow", "Sync the connected logger\'s date and time with this computer\'s date and time "))
        self.actionSync_logger_to_computer_time.setShortcut(_translate("MainWindow", "Ctrl+T"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionTurn_ON.setText(_translate("MainWindow", "Turn ON"))
        self.actionTrun_OFF.setText(_translate("MainWindow", "Trun OFF"))
