# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'real_time_window2.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RealTimeWindow(object):
    def setupUi(self, RealTimeWindow):
        RealTimeWindow.setObjectName("RealTimeWindow")
        RealTimeWindow.resize(400, 334)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(RealTimeWindow.sizePolicy().hasHeightForWidth())
        RealTimeWindow.setSizePolicy(sizePolicy)
        RealTimeWindow.setMinimumSize(QtCore.QSize(300, 200))
        font = QtGui.QFont()
        font.setFamily("Arial")
        RealTimeWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(RealTimeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.hum_lcd = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hum_lcd.sizePolicy().hasHeightForWidth())
        self.hum_lcd.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.hum_lcd.setFont(font)
        self.hum_lcd.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.hum_lcd.setDigitCount(7)
        self.hum_lcd.setProperty("value", 0.0)
        self.hum_lcd.setObjectName("hum_lcd")
        self.gridLayout.addWidget(self.hum_lcd, 3, 2, 1, 1)
        self.live_hum = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.live_hum.sizePolicy().hasHeightForWidth())
        self.live_hum.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.live_hum.setFont(font)
        self.live_hum.setObjectName("live_hum")
        self.gridLayout.addWidget(self.live_hum, 3, 0, 1, 1)
        self.live_temp = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.live_temp.sizePolicy().hasHeightForWidth())
        self.live_temp.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.live_temp.setFont(font)
        self.live_temp.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.live_temp.setObjectName("live_temp")
        self.gridLayout.addWidget(self.live_temp, 2, 0, 1, 1)
        self.live_pre = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.live_pre.sizePolicy().hasHeightForWidth())
        self.live_pre.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.live_pre.setFont(font)
        self.live_pre.setObjectName("live_pre")
        self.gridLayout.addWidget(self.live_pre, 4, 0, 1, 1)
        self.pre_lcd = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pre_lcd.sizePolicy().hasHeightForWidth())
        self.pre_lcd.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.pre_lcd.setFont(font)
        self.pre_lcd.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pre_lcd.setSmallDecimalPoint(False)
        self.pre_lcd.setDigitCount(7)
        self.pre_lcd.setProperty("value", 0.0)
        self.pre_lcd.setProperty("intValue", 0)
        self.pre_lcd.setObjectName("pre_lcd")
        self.gridLayout.addWidget(self.pre_lcd, 4, 2, 1, 1)
        self.temp_lcd = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temp_lcd.sizePolicy().hasHeightForWidth())
        self.temp_lcd.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.temp_lcd.setFont(font)
        self.temp_lcd.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.temp_lcd.setDigitCount(7)
        self.temp_lcd.setProperty("value", 0.0)
        self.temp_lcd.setObjectName("temp_lcd")
        self.gridLayout.addWidget(self.temp_lcd, 2, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 6, 0, 1, 3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_reading_start = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_reading_start.sizePolicy().hasHeightForWidth())
        self.btn_reading_start.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.btn_reading_start.setFont(font)
        self.btn_reading_start.setObjectName("btn_reading_start")
        self.horizontalLayout.addWidget(self.btn_reading_start)
        self.savingText = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.savingText.setFont(font)
        self.savingText.setTextFormat(QtCore.Qt.AutoText)
        self.savingText.setScaledContents(False)
        self.savingText.setObjectName("savingText")
        self.horizontalLayout.addWidget(self.savingText)
        spacerItem1 = QtWidgets.QSpacerItem(100, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btn_reading_stop = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_reading_stop.sizePolicy().hasHeightForWidth())
        self.btn_reading_stop.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.btn_reading_stop.setFont(font)
        self.btn_reading_stop.setObjectName("btn_reading_stop")
        self.horizontalLayout.addWidget(self.btn_reading_stop)
        self.gridLayout.addLayout(self.horizontalLayout, 11, 0, 1, 3)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 9, 0, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.spinBox.setFont(font)
        self.spinBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.spinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(60)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 9, 2, 1, 1)
        RealTimeWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(RealTimeWindow)
        QtCore.QMetaObject.connectSlotsByName(RealTimeWindow)

    def retranslateUi(self, RealTimeWindow):
        _translate = QtCore.QCoreApplication.translate
        RealTimeWindow.setWindowTitle(_translate("RealTimeWindow", "Live Data Streaming"))
        self.live_hum.setText(_translate("RealTimeWindow", "Realtive Humidity (%)"))
        self.live_temp.setText(_translate("RealTimeWindow", "Temperature (C)"))
        self.live_pre.setText(_translate("RealTimeWindow", "Barometric Air Pressure (mbar)"))
        self.btn_reading_start.setText(_translate("RealTimeWindow", "Start"))
        self.savingText.setText(_translate("RealTimeWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">●</span><span style=\" font-size:12pt;\"/>REC</p></body></html>"))
        self.btn_reading_stop.setText(_translate("RealTimeWindow", "Stop"))
        self.label.setText(_translate("RealTimeWindow", "Refresh rate (seconds)"))
